Repository NYUDevOpsInventory/inventory, pull requests merged in 2018-03, with the labels that each got.

#28 Test case added for adding duplicate product information
  tests/test_server.py
Labels: technical debt

#29 API for deleting a product information along with tests.
  server.py
  tests/test_server.py
Labels: enhancement

#30 Initializing logging
  .gitignore
  models.py
  server.py
Labels: technical debt

#35 Tests added for models.py
  models.py
  tests/test_prod_info.py
Labels: Testing, technical debt

#37 tests for listing all entries in the inventory.
  server.py
  tests/test_server.py
Labels: Testing, enhancement

#39 Restock action along with tests.
  models.py
  server.py
  tests/test_prod_info.py
  tests/test_server.py
Labels: Testing, enhancement
